"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""


def get_even_fibonacci_numbers(limit):
    seq = [1, 2]
    while seq[-1] <= limit:
        seq.append(seq[-1] + seq[-2])
    return list(filter(lambda x: x % 2 == 0, seq))


result = get_even_fibonacci_numbers(4000000)
print(sum(result))
